version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./python/dockerfile
    image: "build2022/app:latest"
    container_name: "build2022-app"
    ports:
      - 9000:9000
    environment:
      - FRONT_URL=http://localhost:3000
  
  web:
    build:
      context: .
      dockerfile: ./typescript/simple-mercari-web/dockerfile
    image: "build2022/web:latest"
    container_name: "build2022-web"
    ports:
      - 3000:3000
    environment:
      - API_URL=http://localhost:9000